name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Run make all
        run: make all
